# tasks file for debian-12-mariadb-administration
---
- name: databases | create
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8mb4_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8mb4') }}"
  with_items: "{{ debian_12_mariadb_administration_databases_present }}"

- name: databases | drop
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ debian_12_mariadb_administration_databases_absent }}"
